// ─────────────────────────────────────────────────────────
// DiffDelta — Source Health API
// GET /api/v1/health
// GET /api/v1/health?source=nist_nvd
// GET /api/v1/health?status=error
// Why: Agents need programmatic access to source health so
// they can skip broken sources and route around failures.
// Reads from the static diff/health.json generated by the
// sync pipeline — no KV dependency.
// ─────────────────────────────────────────────────────────

import { jsonResponse, errorResponse } from "../../../_shared/response";
import type { Env } from "../../../_shared/types";

interface HealthSource {
  status: string;
  changed?: boolean;
  stale?: boolean;
  stale_age_sec?: number;
  consecutive_failures?: number;
  error_code?: string;
  fallback_active?: boolean;
  recovery_probe_ok?: boolean;
  reliability?: number;
  last_success?: string;
}

interface HealthData {
  generated_at: string;
  schema_version: string;
  summary: {
    total: number;
    ok: number;
    degraded: number;
    error: number;
    disabled: number;
    health_pct: number;
  };
  sources: Record<string, HealthSource>;
}

export const onRequestGet: PagesFunction<Env> = async (context) => {
  const { request } = context;
  const url = new URL(request.url);
  const sourceFilter = url.searchParams.get("source");
  const statusFilter = url.searchParams.get("status");

  // Fetch the static health.json from CDN (same origin)
  const origin = url.origin;
  let healthData: HealthData;
  try {
    const res = await fetch(`${origin}/diff/health.json`);
    if (!res.ok) {
      return errorResponse("Health data not available yet", 503);
    }
    healthData = (await res.json()) as HealthData;
  } catch {
    return errorResponse("Failed to load health data", 503);
  }

  // Single source lookup
  if (sourceFilter) {
    const sourceHealth = healthData.sources[sourceFilter];
    if (!sourceHealth) {
      return errorResponse(`Source "${sourceFilter}" not found`, 404);
    }
    return jsonResponse({
      source_id: sourceFilter,
      ...sourceHealth,
      _generated_at: healthData.generated_at,
    });
  }

  // Status filter (error, disabled, degraded, ok)
  if (statusFilter) {
    const validStatuses = ["ok", "error", "disabled", "degraded"];
    if (!validStatuses.includes(statusFilter)) {
      return errorResponse(
        `Invalid status filter. Must be one of: ${validStatuses.join(", ")}`,
        400
      );
    }

    const filtered: Record<string, HealthSource> = {};
    for (const [id, src] of Object.entries(healthData.sources)) {
      if (src.status === statusFilter) {
        filtered[id] = src;
      }
    }

    return jsonResponse({
      status_filter: statusFilter,
      count: Object.keys(filtered).length,
      sources: filtered,
      _generated_at: healthData.generated_at,
    });
  }

  // Full health dashboard
  return jsonResponse(healthData);
};
